#!/bin/bash

VERSION=$(echo ${GITHUB_REF#refs/tags/v} | grep '^\d' || echo "sha-$(git rev-parse --short HEAD)")

pushd $(dirname "$0") > /dev/null
cd ..
echo "CURRENT_PROJECT_VERSION = $VERSION" >> Version.xcconfig
popd
