name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "0 0 * * *"
  issue_comment:
    types: [created]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: "This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          stale-pr-message: "This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          days-before-issue-stale: 60
          days-before-pr-stale: 60
          days-before-issue-close: 5
          days-before-pr-close: 10
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: help wanted
          exempt-draft-pr: true
          exempt-assignees: lujjjh
